In [ ]:
# 숫자 3개씩 (가장 기본)

from keras.models import Sequential
from keras.layers import Input, SimpleRNN, Dense

import numpy as np

# ----------------------------
# 데이터
# ----------------------------
x = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])

y = np.array([4,5,6,7])

print(x.shape)

# (4,3) -> (4,3,1)
x = x.reshape(4,3,1)

print(x.shape)

# ----------------------------
# 모델
# ----------------------------
model = Sequential()

model = Sequential([
    Input(shape=(3,1)),
    SimpleRNN(2, activation="relu"),
    Dense(1)
])

model.summary()

# ----------------------------
# 컴파일
# ----------------------------
model.compile(
    optimizer="adam",
    loss="mse"
)

# ----------------------------
# 학습
# ----------------------------
model.fit(
    x,
    y,
    epochs=300,
    verbose=1
)

# ----------------------------
# 예측
# ----------------------------
x_pred = np.array([[5,6,7]])
x_pred = x_pred.reshape(1,3,1)

print(model.predict(x_pred))

(4, 3)
(4, 3, 1)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_4 (SimpleRNN)        │ (None, 2)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11 (44.00 B)

 Trainable params: 11 (44.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 66.8423
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 66.6241
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 66.4070
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 66.1909
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 65.9759
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 65.7620
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 65.5492
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 65.3375
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 65.1270
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 64.9175
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 64.7092
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 64.5021
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 64.2961
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 64.0913
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 63.8876
Epoch 

In [6]:
# 예제 2. 숫자 5개씩
import numpy as np
from keras.models import Sequential
from keras.layers import Input, SimpleRNN, Dense

# ==========================
# 1. 데이터 준비
# ==========================

x = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7]
])

y = np.array([
    6,
    7,
    8
])

print("reshape 전 :", x.shape)

# (3,5) -> (3,5,1)
x = x.reshape(3,5,1)

print("reshape 후 :", x.shape)

# ==========================
# 2. 모델 생성
# ==========================

model = Sequential([
    Input(shape=(5,1)),
    SimpleRNN(4, activation="relu"),
    Dense(1)
])

# 모델 구조 출력
model.summary()

# ==========================
# 3. 컴파일
# ==========================

model.compile(
    optimizer="adam",
    loss="mse"
)

# ==========================
# 4. 학습
# ==========================

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)

# ==========================
# 5. 예측
# ==========================

x_pred = np.array([
    [4,5,6,7,8]
])

x_pred = x_pred.reshape(1,5,1)

pred = model.predict(x_pred)

print("예측 결과 :", pred)

reshape 전 : (3, 5)
reshape 후 : (3, 5, 1)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_5 (SimpleRNN)        │ (None, 4)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29 (116.00 B)

 Trainable params: 29 (116.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 47.9818
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 47.9116
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 47.8412
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 47.7705
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 47.6996
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 47.6285
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 47.5571
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 47.4854
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 47.4135
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 47.3413
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 47.2689
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 47.1962
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 47.1231
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 47.0498
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 46.9763
Epoch 

In [ ]:
# 예제 4. 주식 종가
import numpy as np
from keras.models import Sequential
from keras.layers import Input, SimpleRNN, Dense

# ==========================================
# 1. 데이터 준비
# ==========================================

# 4일간의 종가
x = np.array([
    [50000, 51000, 52000, 53000],
    [51000, 52000, 53000, 54000],
    [52000, 53000, 54000, 55000]
])

# 다음 날 종가
y = np.array([
    54000,
    55000,
    56000
])

print("===== reshape 전 =====")
print(x)
print("Shape :", x.shape)

# (3,4) -> (3,4,1)
x = x.reshape(3, 4, 1)

# data_size = 3
# time_steps = 4
# features = 1 (종가만 사용)  


print("\n===== reshape 후 =====")
print(x)
print("Shape :", x.shape)

# ==========================================
# 2. 모델 생성
# ==========================================

model = Sequential([
    Input(shape=(4,1)),
    SimpleRNN(8, activation="relu"),
    Dense(1)
])

# 모델 구조 확인
model.summary()

# ==========================================
# 3. 컴파일
# ==========================================

model.compile(
    optimizer="adam",
    loss="mse"
)

# ==========================================
# 4. 학습
# ==========================================

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)

# ==========================================
# 5. 예측
# ==========================================

x_pred = np.array([
    [53000,54000,55000,56000]
])

x_pred = x_pred.reshape(1,4,1)

pred = model.predict(x_pred)

print("\n===== 예측 결과 =====")
print("다음 날 예상 종가 :", pred)


===== reshape 전 =====
[[50000 51000 52000 53000]
 [51000 52000 53000 54000]
 [52000 53000 54000 55000]]
Shape : (3, 4)

===== reshape 후 =====
[[[50000]
  [51000]
  [52000]
  [53000]]

 [[51000]
  [52000]
  [53000]
  [54000]]

 [[52000]
  [53000]
  [54000]
  [55000]]]
Shape : (3, 4, 1)


Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_6 (SimpleRNN)        │ (None, 8)              │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 89 (356.00 B)

 Trainable params: 89 (356.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 2663061248.0000
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2658063616.0000
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2653025280.0000
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2647944960.0000
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2642822400.0000
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2637656320.0000
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2632446464.0000
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2627191552.0000
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2621890560.0000
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2616542976.0000
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2611147520.0000
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 2605703424.0000
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2600210176.0000
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━

In [8]:
# 좋습니다. 이번 예제는 feature가 2개인 경우입니다.

# Feature 1 : 온도(Temperature)
# Feature 2 : 습도(Humidity)

# 즉, 3일간의 온도와 습도를 보고 다음 날의 온도를 예측하는 예제입니다.

import numpy as np
from keras.models import Sequential
from keras.layers import Input, SimpleRNN, Dense

# ==========================================
# 1. 데이터 준비
# ==========================================

# [온도, 습도]
x = np.array([
    [[20,60],[21,61],[22,62]],
    [[23,63],[24,64],[25,65]],
    [[26,66],[27,67],[28,68]]
])

# 다음 날 온도
y = np.array([
    23,
    26,
    29
])

print("===== 입력 데이터 =====")
print(x)

x = x.reshape(-1,3,2)

print("\nShape :", x.shape)

# ==========================================
# data_size = 3
# time_steps = 3
# features = 2
# ==========================================

# ==========================================
# 2. 모델 생성
# ==========================================

model = Sequential([
    Input(shape=(3,2)),
    SimpleRNN(8, activation="relu"),
    Dense(1)
])

model.summary()

# ==========================================
# 3. 컴파일
# ==========================================

model.compile(
    optimizer="adam",
    loss="mse"
)

# ==========================================
# 4. 학습
# ==========================================

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)

# ==========================================
# 5. 예측
# ==========================================

x_pred = np.array([
    [[29,69],
     [30,70],
     [31,71]]
])

pred = model.predict(x_pred)

print("\n===== 예측 결과 =====")
print("다음 날 예상 온도 :", pred)

===== 입력 데이터 =====
[[[20 60]
  [21 61]
  [22 62]]

 [[23 63]
  [24 64]
  [25 65]]

 [[26 66]
  [27 67]
  [28 68]]]

Shape : (3, 3, 2)


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_7 (SimpleRNN)        │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 742.8441
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 726.6804
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 710.7109
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 694.9387
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 679.3664
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 663.9972
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 648.8329
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 633.8763
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 619.1286
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 604.5922
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 590.2688
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 576.1592
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 562.2648
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 548.5871
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 266ms/step

===== 예측 결과 =====
다음 날 예상 온도 : [[28.564213]]


In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Input, SimpleRNN, Dense

# ==========================================
# 1. 데이터 준비
# ==========================================

# [키(cm), 몸무게(kg), 나이]
x = np.array([
    [[170,60,20], [171,61,21]],
    [[180,70,30], [181,71,31]],
    [[190,80,40], [191,81,41]],
    [[200,90,50], [201,91,51]]
])

# 다음 해 키
y = np.array([
    172,
    182,
    192,
    202
])

print("===== 입력 데이터 =====")
print(x)

print("\nShape :", x.shape)



# 좋은 질문입니다.
# 사실 제가 예제를 만들기 위해 2로 설정한 것일 뿐, 반드시 2여야 하는 것은  아님
# RNN에서 **time_steps는 "과거를 몇 개 볼 것인가?"**를 의미

# x = x.reshape(-1,4,2) 
# 4로 해도 됨



# ==========================================
# data_size = 4
# time_steps = 2
# features = 3
# ==========================================

# ==========================================
# 2. 모델 생성
# ==========================================

model = Sequential([
    Input(shape=(2,3)),
    SimpleRNN(8, activation="relu"),
    Dense(1)
])

model.summary()

# ==========================================
# 3. 컴파일
# ==========================================

model.compile(
    optimizer="adam",
    loss="mse"
)

# ==========================================
# 4. 학습
# ==========================================

model.fit(
    x,
    y,
    epochs=500,
    verbose=1
)

# ==========================================
# 5. 예측
# ==========================================

x_pred = np.array([
    [
        [210,95,25],
        [211,96,26]
    ]
])

pred = model.predict(x_pred)

print("\n===== 예측 결과 =====")
print("다음 해 예상 키 :", pred)

===== 입력 데이터 =====
[[[170  60  20]
  [171  61  21]]

 [[180  70  30]
  [181  71  31]]

 [[190  80  40]
  [191  81  41]]

 [[200  90  50]
  [201  91  51]]]

Shape : (4, 2, 3)


Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_9 (SimpleRNN)        │ (None, 8)              │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 105 (420.00 B)

 Trainable params: 105 (420.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500


ValueError: Exception encountered when calling SimpleRNNCell.call().

Dimensions must be equal, but are 2 and 3 for '{{node sequential_10_1/simple_rnn_9_1/simple_rnn_cell_1/MatMul}} = MatMul[T=DT_FLOAT, grad_a=false, grad_b=false, transpose_a=false, transpose_b=false](sequential_10_1/simple_rnn_9_1/strided_slice_2, sequential_10_1/simple_rnn_9_1/simple_rnn_cell_1/Cast/ReadVariableOp)' with input shapes: [?,2], [3,8].

Arguments received by SimpleRNNCell.call():
  • sequence=tf.Tensor(shape=(None, 2), dtype=float32)
  • states=('tf.Tensor(shape=(None, 8), dtype=float32)',)
  • training=True