# 📊 Multinomial Naive Bayes 간단 예제 + 설명 (Velog용)

> ✔ 횟수 기반 확률 분류 모델  
> ✔ 텍스트 분류에서 많이 사용  
> ✔ 단어 “등장 횟수”가 핵심

---

# 🧠 1. Multinomial Naive Bayes란?

👉 한 줄 정의:

> **“feature의 존재 여부가 아니라 ‘몇 번 등장했는지(횟수)’를 이용해 분류하는 나이브 베이즈”**

---

# 🍪 2. 직관 예제

## 🎯 상황: 시험 합격 예측

| 학생 | 공부 횟수 | 과제 횟수 | 출석 횟수 | 합격 |
|------|----------|----------|----------|------|
| A | 5 | 3 | 10 | 1 |
| B | 4 | 2 | 9 | 1 |
| C | 1 | 0 | 5 | 0 |
| D | 0 | 1 | 4 | 0 |

---

## 📌 핵심 차이

| 모델 | 기준 |
|------|------|
| BernoulliNB | 했냐 / 안 했냐 (0/1) |
| MultinomialNB | 몇 번 했냐 (count) |

---

# 📐 3. 핵심 아이디어

:contentReference[oaicite:0]{index=0}

---

## 🧠 의미

| 기호 | 의미 |
|------|------|
| nᵢ | 특정 feature 등장 횟수 |
| ∑n | 전체 횟수 |
| V | feature 개수 |
| α | smoothing (0 방지) |

---

In [ ]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 공부 / 과제 / 출석 (횟수 데이터)
X = np.array([
    [5,3,10],
    [4,2,9],
    [1,0,5],
    [0,1,4],
    [6,4,10],
    [1,1,3],
    [7,5,12],
    [3,2,8],
    [2,1,6],
    [0,0,2]
])

y = [1,1,0,0,1,0,1,1,0,0]

# 현재 데이터
# X = [
#     [5,3,10],  # y=1
#     [4,2,9],   # y=1
#     [1,0,5],   # y=0
#     [0,1,4],   # y=0
#     [6,4,10],  # y=1
#     [1,1,3],   # y=0
#     [7,5,12],  # y=1
#     [3,2,8],   # y=1
#     [2,1,6],   # y=0
#     [0,0,2]    # y=0
# ]

# 🎯 2. 우리가 예측할 값
# x = [7, 5, 12]

# 🧠 3. 클래스 나누기
# ✔ y = 1 (합격)
# [5,3,10]
# [4,2,9]
# [6,4,10]
# [7,5,12]
# [3,2,8]

# ✔ y = 0 (불합격)
# [1,0,5]
# [0,1,4]
# [1,1,3]
# [2,1,6]
# [0,0,2]

# 📐 4. 사전 확률 P(y)
# P(y=1)=5/10=0.5
# P(y=0)=5/10=0.5

# 📊 5. feature별 확률 계산

# 🟢 (1) y = 1일 때
# 📌 공부 = 7

# y=1 데이터:

# [5,4,6,7,3]

# 👉 7은 1번 등장

# P(공부=7∣y=1)=1/5=0.2

# 📌 과제 = 5
# [3,2,4,5,2]

# 👉 5는 1번 등장

# P(과제=5∣y=1)=1/5=0.2

# 📌 출석 = 12
# [10,9,10,12,8]

# 👉 12는 1번 등장

# P(출석=12∣y=1)=1/5=0.2

# 🧮 최종 y=1 확률

# P(y=1∣x)∝0.5×0.2×0.2×0.2

# 계산:

# = 0.5 × 0.008
# = 0.004

# 🔴 (2) y = 0일 때
# 📌 공부 = 7
# [1,0,1,2,0]

# 👉 7 없음 → 0 (문제 발생🔥)

# 📌 여기서 핵심 문제

# P(공부=7∣y=0)=0

# ❗ 그러면 전체:

# P(y=0∣x)=0×P(과제∣y=0)×P(출석∣y=0)=0

# 💥 6. 최종 비교
# 클래스	확률
# y=1	0.004
# y=0	0

# 🏁 7. 결과
#➡ y = 1 (무조건 선택)

# ⚠️ 8. 여기서 중요한 문제
# 👉 y=0은 사실 틀린 게 아니라
# "데이터에 7이라는 값이 없어서 확률이 0이 된 것"

# 🧠 9. 핵심 깨달음

# Multinomial NB 문제는 이거야:

# ❌ 한 번도 안 본 값 → 확률 0

# 그래서:

# 새로운 데이터 나오면 쉽게 망함
# Accuracy 흔들림

# 🚀 한 줄 요약
# 👉 Multinomial Naive Bayes는 각 feature 확률을 하나씩 곱하는데, 학습 데이터에 없는 값이 나오면 확률이 0이 되어 전체 결과가 무너질 수 있다

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
)

print("X_train:", X_train)
print("y_train:", y_train)

print("X_test:", X_test)
print("y_test:", y_test)

X_train: [[ 5  3 10]
 [ 3  2  8]
 [ 1  0  5]
 [ 0  0  2]
 [ 6  4 10]
 [ 0  1  4]
 [ 7  5 12]]
y_train: [1, 1, 0, 0, 1, 0, 1]
X_test: [[2 1 6]
 [4 2 9]
 [1 1 3]]
y_test: [0, 1, 0]


In [8]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [9]:
y_pred = model.predict(X_test)
print("예측 결과:", y_pred)

예측 결과: [1 1 1]


In [10]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.3333333333333333
